version: '3'
services:
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017

  api:
    image: sample-express-app
    build: .
    links:
      - mongo
    ports:
      - "8080:8080"
    environment:
      # - MONGODB_URL=mongodb://mongo:27017/linkTree
      - MONGODB_URL=mongodb+srv://dashmandalsaikhanbileg:amazon@testamazon.4lbhbua.mongodb.net/linkTree?retryWrites=true&w=majority
