name: Link tree push action

on:
  push:
    branches: [master, main]

env:
  CI: true
  ATLAS_URI: mongodb+srv://dashmandalsaikhanbileg:amazon@testamazon.4lbhbua.mongodb.net/?retryWrites=true&w=majority
  JWT_SECRET: LINKTREE%21$
  JWT_EXPIRESIN: 30d

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Node dependency install
        run: cd server && yarn

      - name: Run test
        run: cd server && npx jest