name: Link tree push action

on:
  push:
    branches: [master, main]
defaults:
  run:
    working-directory: "./server"
env:
  CI: true
  ATLAS_URI: mongodb+srv://dashmandalsaikhanbileg:amazon@testamazon.4lbhbua.mongodb.net/?retryWrites=true&w=majority
  JWT_SECRET: LINKTREE%21$
  JWT_EXPIRESIN: 30d
  VERCEL_TOKEN: pESGlMFX2aHyl2B0OeJWO7qG

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Node dependency install
        run: yarn

      - name: Run test
        run: npx jest
      
      # - name: Deploy
      #   run: vercel
      - name: "Deploy application"
        run: vercel --token ${VERCEL_TOKEN} --prod
         